services:
  - type: web
    name: shynli-com
    runtime: node
    repo: https://github.com/miralitys/shynlicom.git
    branch: main
    buildCommand: npm ci && npm run build
    startCommand: npm start
    domains:
      - shynli.com
      - www.shynli.com
